name: Close inactive issues
on:
  schedule:
    - cron: "30 6 * * *"

jobs:
  close-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/stale@v10
        with:
          days-before-issue-stale: 28
          days-before-issue-close: 0
          only-labels: "invalid"
          close-issue-message: "This issue has been automatically closed because it was marked as invalid and received no response in 28 days."
