name: Close Invalid Issues and PRs

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight UTC

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          days-before-stale: 28  # 4 weeks before marking as stale
          days-before-close: 0   # Close immediately after being marked stale
          stale-issue-label: "invalid"
          stale-pr-label: "invalid"
          close-issue-message: "This issue has been automatically closed because it was marked as invalid and received no response in 4 weeks."
          close-pr-message: "This pull request has been automatically closed because it was marked as invalid and received no response in 4 weeks."
